"""create movie cache tables

Revision ID: 09ca39bec644
Revises: 
Create Date: 2026-04-26 12:03:26.973582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ca39bec644'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_details_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_details_cache_expires_at'), 'movie_details_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_movie_details_cache_id'), 'movie_details_cache', ['id'], unique=False)
    op.create_index(op.f('ix_movie_details_cache_tmdb_id'), 'movie_details_cache', ['tmdb_id'], unique=True)
    op.create_table('movie_search_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_search_cache_expires_at'), 'movie_search_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_movie_search_cache_id'), 'movie_search_cache', ['id'], unique=False)
    op.create_index(op.f('ix_movie_search_cache_query'), 'movie_search_cache', ['query'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_search_cache_query'), table_name='movie_search_cache')
    op.drop_index(op.f('ix_movie_search_cache_id'), table_name='movie_search_cache')
    op.drop_index(op.f('ix_movie_search_cache_expires_at'), table_name='movie_search_cache')
    op.drop_table('movie_search_cache')
    op.drop_index(op.f('ix_movie_details_cache_tmdb_id'), table_name='movie_details_cache')
    op.drop_index(op.f('ix_movie_details_cache_id'), table_name='movie_details_cache')
    op.drop_index(op.f('ix_movie_details_cache_expires_at'), table_name='movie_details_cache')
    op.drop_table('movie_details_cache')
    # ### end Alembic commands ###
